import { createClient } from 'npm:@supabase/supabase-js@2'
import { SignJWT, importPKCS8 } from 'npm:jose@5'

const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'}
const norm=(v:string)=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()
const findCol=(h:string[],terms:string[])=>h.findIndex(x=>terms.some(t=>norm(x).includes(t)))
const dateISO=(v:any)=>{if(!v)return null;const s=String(v).trim();let m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(m)return `${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:null}
async function accessToken(){const email=Deno.env.get('GOOGLE_SERVICE_ACCOUNT_EMAIL')!,pk=(Deno.env.get('GOOGLE_PRIVATE_KEY')||'').replace(/\\n/g,'\n');const key=await importPKCS8(pk,'RS256');const now=Math.floor(Date.now()/1000);const jwt=await new SignJWT({scope:'https://www.googleapis.com/auth/spreadsheets.readonly'}).setProtectedHeader({alg:'RS256',typ:'JWT'}).setIssuer(email).setSubject(email).setAudience('https://oauth2.googleapis.com/token').setIssuedAt(now).setExpirationTime(now+3600).sign(key);const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:jwt})});if(!r.ok)throw new Error(await r.text());return (await r.json()).access_token}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const auth=req.headers.get('Authorization')||'';const sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SECRET_KEY')!,{global:{headers:{Authorization:auth}}});const token=auth.replace('Bearer ','');const {data:{user},error:ue}=await sb.auth.getUser(token);if(ue||!user)throw new Error('Usuário não autenticado');const {data:p,error:pe}=await sb.from('profiles').select('organization_id').eq('id',user.id).single();if(pe)throw pe;const body=await req.json();const id=(body.spreadsheetUrl||'').match(/\/d\/([a-zA-Z0-9-_]+)/)?.[1];if(!id)throw new Error('Link da planilha inválido');const tok=await accessToken();const meta=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${id}?fields=sheets.properties`,{headers:{Authorization:`Bearer ${tok}`}});if(!meta.ok)throw new Error(await meta.text());const sheets=(await meta.json()).sheets||[];let items:any[]=[];for(const sh of sheets){const name=sh.properties.title;const vr=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values/${encodeURIComponent(name)}?majorDimension=ROWS&valueRenderOption=FORMATTED_VALUE`,{headers:{Authorization:`Bearer ${tok}`}});if(!vr.ok)continue;const rows=(await vr.json()).values||[];let hi=rows.findIndex((r:any[])=>r.some(c=>/respons[aá]vel/i.test(String(c)))&&r.some(c=>/status|prazo|objetivo|etapa/i.test(String(c))));if(hi<0)hi=rows.findIndex((r:any[])=>r.filter(Boolean).length>=3);if(hi<0)continue;const h=rows[hi].map(String),ci={task:findCol(h,['objetivos especificos','tarefa','acao','etapa','atividade']),owner:findCol(h,['responsavel','dono']),status:findCol(h,['status','situacao']),due:findCol(h,['prazo','data']),kpi:findCol(h,['kpi','indicador']),priority:findCol(h,['prioridade']),company:findCol(h,['empresa'])};let objective='';for(let i=hi+1;i<rows.length;i++){const r=rows[i],title=String(r[ci.task>=0?ci.task:1]||'').trim();if(!title)continue;const owner=ci.owner>=0?String(r[ci.owner]||'').trim():'';const st=ci.status>=0?String(r[ci.status]||'').trim():'';const due=ci.due>=0?dateISO(r[ci.due]):null;const looksObjective=!owner&&!st&&!due&&(String(r[0]||'').trim()||title.length>70);if(looksObjective){objective=title;items.push({organization_id:p.organization_id,source_key:`${name}:${i+1}:objective`,sheet_name:name,source_row:i+1,record_type:'Objetivo',objective,title,status:'Em andamento',raw:r});continue}items.push({organization_id:p.organization_id,source_key:`${name}:${i+1}:task`,sheet_name:name,source_row:i+1,record_type:'Tarefa',objective,title,owner,status:st||'Pendente',due_date:due,kpi:ci.kpi>=0?String(r[ci.kpi]||''):null,priority:ci.priority>=0?String(r[ci.priority]||''):null,company:ci.company>=0?String(r[ci.company]||''):null,raw:r})}}
const admin=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SECRET_KEY')!);await admin.from('strategic_items').delete().eq('organization_id',p.organization_id);for(let i=0;i<items.length;i+=500){const {error}=await admin.from('strategic_items').upsert(items.slice(i,i+500),{onConflict:'organization_id,source_key'});if(error)throw error}await admin.from('google_sheet_sources').upsert({organization_id:p.organization_id,spreadsheet_id:id,spreadsheet_url:body.spreadsheetUrl,last_synced_at:new Date().toISOString()},{onConflict:'organization_id,spreadsheet_id'});await admin.from('sync_logs').insert({organization_id:p.organization_id,status:'Sucesso',item_count:items.length,details:{sheets:sheets.length}});return new Response(JSON.stringify({ok:true,count:items.length,sheets:sheets.length}),{headers:{...cors,'content-type':'application/json'}})}catch(e){return new Response(JSON.stringify({error:String(e.message||e)}),{status:400,headers:{...cors,'content-type':'application/json'}})}})
