(function(){
  const C=window.SIGE_CONFIG||{};
  const enabled=!!(C.supabaseUrl&&C.supabasePublishableKey&&!C.supabaseUrl.includes('SEU-PROJETO'));
  let client=null,user=null,orgId=null,saveTimer=null,remoteVersion=0,applyingRemote=false,channel=null;
  function status(text,ok=true){let e=document.getElementById('cloudStatus');if(e){e.textContent=text;e.style.background=ok?'#dcfce7':'#fee2e2';e.style.color=ok?'#166534':'#991b1b'}}
  function injectUI(){
    const style=document.createElement('style');style.textContent=`#cloudAuth{position:fixed;inset:0;background:linear-gradient(135deg,#0d263e,#1f6aa5);z-index:9999;display:flex;align-items:center;justify-content:center;padding:20px}.cloud-card{background:#fff;width:min(430px,100%);border-radius:20px;padding:24px;box-shadow:0 20px 60px #0004}.cloud-card input{width:100%;margin:6px 0 12px}.cloudbar{position:fixed;right:14px;bottom:14px;z-index:60;display:flex;gap:6px;align-items:center;background:#fff;border:1px solid #d9e1ea;border-radius:12px;padding:7px;box-shadow:0 5px 20px #0002}.cloudbar button{border:0;border-radius:8px;padding:7px 9px;cursor:pointer}.cloudbar span{font-size:12px;padding:6px 8px;border-radius:8px}`;document.head.appendChild(style);
    const bar=document.createElement('div');bar.className='cloudbar';bar.innerHTML=`<span id="cloudStatus">${enabled?'Conectando...':'Modo local'}</span><button onclick="SIGECloud.syncSheets()">☁️ Sincronizar planilha</button><button onclick="SIGECloud.backupNow()">🛡️ Backup nuvem</button><button onclick="SIGECloud.signOut()">Sair</button>`;document.body.appendChild(bar);
  }
  function authScreen(){let d=document.createElement('div');d.id='cloudAuth';d.innerHTML=`<div class="cloud-card"><h1>SIGE IP</h1><p>Plataforma executiva em nuvem</p><label>E-mail</label><input id="cloudEmail" type="email" autocomplete="email"><label>Senha</label><input id="cloudPassword" type="password" autocomplete="current-password"><div style="display:flex;gap:8px"><button class="btn" onclick="SIGECloud.signIn()">Entrar</button><button class="btn sec" onclick="SIGECloud.signUp()">Criar conta</button></div><p id="cloudMsg" class="muted"></p></div>`;document.body.appendChild(d)}
  async function init(){injectUI();if(!enabled){status('Modo local — configure config.js',false);return {enabled:false}};client=supabase.createClient(C.supabaseUrl,C.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});let {data:{session}}=await client.auth.getSession();if(!session){authScreen();return new Promise(resolve=>{window.__sigeAuthResolve=resolve})}return afterAuth(session.user)}
  async function afterAuth(u){user=u;document.getElementById('cloudAuth')?.remove();const {data:p,error}=await client.from('profiles').select('organization_id,role').eq('id',u.id).single();if(error)throw error;orgId=p.organization_id;status('Nuvem conectada');subscribe();return {enabled:true,user,orgId,state:await loadState()}}
  async function signIn(){msg('Entrando...');let {data,error}=await client.auth.signInWithPassword({email:val('cloudEmail'),password:val('cloudPassword')});if(error)return msg(error.message);let r=await afterAuth(data.user);window.__sigeAuthResolve?.(r)}
  async function signUp(){msg('Criando conta...');let {data,error}=await client.auth.signUp({email:val('cloudEmail'),password:val('cloudPassword')});if(error)return msg(error.message);if(!data.session)return msg('Conta criada. Verifique seu e-mail para confirmar.');let r=await afterAuth(data.user);window.__sigeAuthResolve?.(r)}
  async function signOut(){if(client)await client.auth.signOut();location.reload()}
  function val(id){return document.getElementById(id)?.value||''}function msg(t){let e=document.getElementById('cloudMsg');if(e)e.textContent=t}
  async function loadState(){if(!orgId)return null;let {data,error}=await client.from('app_states').select('data,version').eq('organization_id',orgId).maybeSingle();if(error)throw error;if(data){remoteVersion=data.version||0;return data.data}return null}
  async function firstUpload(local){if(!orgId)return;let payload={organization_id:orgId,data:local,version:1,updated_by:user.id};let {error}=await client.from('app_states').upsert(payload,{onConflict:'organization_id'});if(error)throw error;remoteVersion=1;await backupNow('Migração inicial do banco local')}
  function queueSave(data){if(!enabled||!orgId||applyingRemote)return;clearTimeout(saveTimer);saveTimer=setTimeout(()=>pushState(data),700)}
  async function pushState(data){try{let next=remoteVersion+1;let {error}=await client.from('app_states').upsert({organization_id:orgId,data,version:next,updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:'organization_id'});if(error)throw error;remoteVersion=next;status('Salvo na nuvem às '+new Date().toLocaleTimeString('pt-BR'))}catch(e){status('Falha ao salvar: '+e.message,false)}}
  function subscribe(){if(channel)client.removeChannel(channel);channel=client.channel('sige-state-'+orgId).on('postgres_changes',{event:'UPDATE',schema:'public',table:'app_states',filter:'organization_id=eq.'+orgId},p=>{if((p.new.version||0)<=remoteVersion)return;remoteVersion=p.new.version;applyingRemote=true;window.db=p.new.data;try{window.migrate?.();window.idbPut?.('app',window.db,'main');window.renderAll?.();status('Atualizado em tempo real')}finally{setTimeout(()=>applyingRemote=false,200)}}).subscribe()}
  async function backupNow(reason='Backup manual'){if(!orgId)return alert('Nuvem não configurada.');let {error}=await client.from('app_backups').insert({organization_id:orgId,data:window.db,reason,created_by:user.id});if(error)return alert(error.message);status('Backup em nuvem criado')}
  async function syncSheets(){if(!client)return alert('Configure e entre no Supabase.');status('Sincronizando Google Sheets...');let {data,error}=await client.functions.invoke('sync-google-sheets',{body:{spreadsheetUrl:C.spreadsheetUrl||window.db?.settings?.googleConnector?.url}});if(error){status('Erro na planilha: '+error.message,false);return alert(error.message)};let {data:rows,error:e2}=await client.from('strategic_items').select('*').eq('organization_id',orgId).order('sheet_name').order('source_row');if(e2)return alert(e2.message);window.db.googlePlanning=(rows||[]).map(x=>({id:x.source_key,objective:x.objective||'',axis:x.axis||'',title:x.title||'',company:x.company||'',responsible:x.owner||'',dueDate:x.due_date||'',kpi:x.kpi||'',priority:x.priority||'',status:x.status||'Pendente',nextDate:x.next_review||'',notes:x.notes||'',sourceSheet:x.sheet_name,sourceRow:x.source_row,recordType:x.record_type||'Tarefa',attachments:[]}));await window.save?.();window.renderAll?.();status(`${data?.count||rows?.length||0} itens sincronizados`)}
  window.SIGECloud={init,signIn,signUp,signOut,queueSave,firstUpload,backupNow,syncSheets,get enabled(){return enabled}};
})();
